[project]
name = "rsvt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Lucius", email = "134286838+luciusneo1017@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.1",
    "pandas>=3.0.5",
]

[project.scripts]
rsvt = "rsvt:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
